[www]
; The user and group under which the pool of processes will run
user = www-data
group = www-data

; The address on which to accept FastCGI requests (port 9000 for all network interfaces)
listen = 9000

; Process management settings
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Clear environment in DevOps containers is false to catch .env variables - можем читать пароли
clear_env = no
